export const PARSE_JOB_REQUEST = 'PARSE_JOB_REQUEST';
export const PARSE_JOB_SUCCESS = 'PARSE_JOB_SUCCESS';
export const PARSE_JOB_FAIL = 'PARSE_JOB_FAIL';

export const ADD_JOB_REQUEST = 'ADD_JOB_REQUEST';
export const ADD_JOB_SUCCESS = 'ADD_JOB_SUCCESS';
export const ADD_JOB_FAIL = 'ADD_JOB_FAIL';

export const GET_JOB_REQUEST = 'GET_JOB_REQUEST';
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS';
export const GET_JOB_FAIL = 'GET_JOB_FAIL';
