export const SAVE_TEMPLATE_REQUEST = 'SAVE_TEMPLATE_REQUEST';
export const SAVE_TEMPLATE_SUCCESS = 'SAVE_TEMPLATE_SUCCESS';
export const SAVE_TEMPLATE_FAIL = 'SAVE_TEMPLATE_FAIL';

export const CREATE_COVERLETTER_REQUEST = 'CREATE_COVERLETTER_REQUEST';
export const CREATE_COVERLETTER_SUCCESS = 'CREATE_COVERLETTER_SUCCESS';
export const CREATE_COVERLETTER_FAIL = 'CREATE_COVERLETTER_FAIL';
